name: HEP Software Foundation Newsletter
description: News from the HEP Software Foundation
url: http://news.hepsoftwarefoundation.org
excerpt_separator: <!--more-->
timezone: Switzerland/Geneva
highlighter: rouge
future: true
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  activities:
    output: true
    permalink: /activities/:title.html


